### ISSUE TITLE
Add support for local variables in functions

### ISSUE THREAD

**Issue by cubed-guy** [acmpesuecc/ice#13]
Variables declared in functions should be declared as local variables.

**Comment by SNEH-17PATEL** [comment]
CAN I GET ASSIGNED??????

**Comment by skandesh-kk** [comment]
pls assign this to me

**Comment by Suhaniverma2004** [comment]
can i get assigned?

**Comment by Manvith-M-Nayak** [comment]
can i get assigned???

**Comment by Ritwik-Ag** [comment]
can i get assigned

**Comment by cubed-guy** [comment]
@SNEH-17PATEL Please tell if you've made progress

**Comment by entity012** [comment]
assign me

**Comment by entity012** [comment]
can i be assigned?

**Comment by M-SriVidya** [comment]
can I get assigned to this?

**Comment by HackerGlory** [comment]
Please assign me to this
